### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by isaacrlevin** [alenny/angular2-adal-example#7]
Got above error running sample gulp file, here is the npm log

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files (x86)\nodejs\\node.exe',
> 1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@2.7.4
> 3 info using node@v0.12.2
> 4 verbose node symlink C:\Program Files (x86)\nodejs\node.exe
> 5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 6 info prebuild angular2-azure-ad@1.0.0
> 7 info build angular2-azure-ad@1.0.0
> 8 verbose unsafe-perm in lifecycle true
> 9 info angular2-azure-ad@1.0.0 Failed to exec build script
> 10 verbose stack Error: angular2-azure-ad@1.0.0 build: `tsc`
> 10 verbose stack Exit status 2
> 10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
> 10 verbose stack     at EventEmitter.emit (events.js:110:17)
> 10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
> 10 verbose stack     at ChildProcess.emit (events.js:110:17)
> 10 verbose stack     at maybeClose (child_process.js:1015:16)
> 10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 11 verbose pkgid angular2-azure-ad@1.0.0
> 12 verbose cwd C:\Users\IsaacLevin\Downloads\angular2-adal-example-master
> 13 error Windows_NT 6.3.9600
> 14 error argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
> 15 error node v0.12.2
> 16 error npm  v2.7.4
> 17 error code ELIFECYCLE
> 18 error angular2-azure-ad@1.0.0 build: `tsc`
> 18 error Exit status 2
> 19 error Failed at the angular2-azure-ad@1.0.0 build script 'tsc'.
> 19 error This is most likely a problem with the angular2-azure-ad package,
> 19 error not with npm itself.
> 19 error Tell the author that this fails on your system:
> 19 error     tsc
> 19 error You can get their info via:
> 19 error     npm owner ls angular2-azure-ad
> 19 error There is likely additional logging output above.
> 20 verbose exit [ 1, true ]

**Comment by Anaia** [comment]
gulp build is still failing with the above errors.

**Comment by kvbhaskar7** [comment]
Same here. i also stuck with the same issue. Has anyone found the fix for this issue? Please help...

> 

1 silly lifecycle angular2-azure-ad@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite" ' ]
12 silly lifecycle angular2-azure-ad@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle angular2-azure-ad@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-azure-ad@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-azure-ad@1.0.0
16 verbose cwd C:\Users\me\Downloads\angular2-adal-example-master\angular2-adal-example-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular2-azure-ad@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 2
23 error Failed at the angular2-azure-ad@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-azure-ad package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-azure-ad
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-azure-ad
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
>
